import { execFile } from "node:child_process";
import { readdir } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { repoRoot } from "./helpers/fixtures.js";

const execFileAsync = promisify(execFile);

// Responsibility: every file a fixture project is made of has to be in the
// repository. A test reads a fixture from disk, so a fixture file that git
// does not carry passes on the machine that created it and fails on every
// clone, which is the worst shape a failure can take: the author cannot see
// it and nobody else can avoid it.
//
// This is not hypothetical. `.gitignore` excludes `.env` and `.env.*`, and a
// negation was added for `.env.*` under tests/fixtures once the pattern ate
// one. The bare `.env` case was missed, so `tests/fixtures/env-reads-project/
// .env` stayed ignored and three tests in tests/env-reads.test.ts passed
// locally and failed the first time they ran anywhere else.
//
// The question asked here is "is this path tracked", not "is it ignored",
// because those come apart: an ignored file and a merely-forgotten one are
// both absent from a clone, and both break the same way.
const FIXTURE_DIR = "tests/fixtures";

// Finder writes these into any directory it is asked to display. They are
// nobody's test data, and failing on one would make this check something to
// be silenced rather than read.
const OS_NOISE = new Set([".DS_Store"]);

// A test that runs against a fixture in place leaves the tool's own output
// inside it. That output is regenerated by the next run and belongs in no
// clone, so it is the one thing here that is absent on purpose.
function isToolOutput(file: string): boolean {
  return file.split(path.sep).includes(".nukadoko");
}

async function listFilesOnDisk(dir: string): Promise<string[]> {
  const entries = await readdir(path.join(repoRoot, dir), { withFileTypes: true, recursive: true });
  return entries
    .filter((entry) => entry.isFile() && !OS_NOISE.has(entry.name))
    .map((entry) => path.relative(repoRoot, path.join(entry.parentPath, entry.name)))
    .filter((file) => !isToolOutput(file));
}

async function listFilesTrackedByGit(dir: string): Promise<Set<string>> {
  const { stdout } = await execFileAsync("git", ["ls-files", "--", dir], { cwd: repoRoot });
  return new Set(stdout.split("\n").filter((line) => line.length > 0));
}

describe("fixture files are in the repository", () => {
  it("finds every file under tests/fixtures tracked by git", async () => {
    const [onDisk, tracked] = await Promise.all([
      listFilesOnDisk(FIXTURE_DIR),
      listFilesTrackedByGit(FIXTURE_DIR),
    ]);

    // Sorted so a run that turns up several names reports them in an order
    // that does not depend on how the directory happened to be walked.
    const untracked = onDisk.filter((file) => !tracked.has(file)).sort();

    expect(untracked, `these fixture files exist here but not in a clone: ${untracked.join(", ")}`).toEqual([]);
  });
});
